# Generated by Django 2.2 on 2022-04-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefedditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeddItem',
            new_name='ProfileFeedItem',
        ),
    ]
